### ISSUE TITLE
[DevOps] Implement GitLab For AirGap Charts For RKE1 

### ISSUE THREAD

**Issue by irishgordo** [harvester/tests#1316]
# Reason
When RKE1 is airgapped utilizing a flow that takes the shape of:

1. `sudo virt-customize -v -x -a jammy-server-cloudimg-amd64-disk-kvm.img --install qemu-guest-agent,docker.io --run-command 'systemctl enable docker.service && systemctl disable apparmor'`
2. ensuring rke node template is built out with:
    a. insecure registries -> Registry Domain: "airgap-docker-registry.192.168.120.236.sslip.io:5000"
    b. registry mirrors -> Mirror URL: "https://airgap-docker-registry.192.168.120.236.sslip.io:5000"
    c. Engine Options -> Storage -> `overlay2`
    d. Install URL for Docker set to "None" (ex, we don't want it set to: `https://releases.rancher.com/install-docker/24.0.sh` ), since the guest-image already has Docker setup
3. ensuring when the RKE1 cluster is being created that Private Registry -> "Enabled" -> URL: "airgap-docker-registry.192.168.120.236.sslip.io" is set
4. additionally, with a VM that has a cloud-config/cloud-init that takes the shape of:
```
#cloud-config
bootcmd:
  - echo 192.168.120.175 airgap-docker-registry.192.168.120.175.sslip.io >>
    /etc/hosts
  - echo 192.168.120.41 rancher.192.168.120.41.sslip.io >> /etc/hosts
chpasswd:
  expire: false
network:
  config:
    - address:
        - 192.168.120.237
      type: nameserver
  version: 1
ntp:
  servers:
    - 192.168.120.26
password: password
```

The RKE1 cluster will provision.
But the Charts will not be able to be pulled down, because, of course - this is airgapped.

We need to fork charts and run a small GitLab instance to fix this.

The GitLab instance must be able to be accessed by the RKE1 instance, but it itself may not necessarily be fully airgapped. Or it could be once the Charts repo is cloned down.

We set this up manually by:
- having a VM with NIC connectivity to the airgapped RKE1 cluster
- cloning down the charts repo
- installing `gitlab-ce` with something like: `sudo GITLAB_ROOT_PASSWORD="testtesttest" EXTERNAL_URL="http://gitserver.192.168.104.197.sslip.io" apt install gitlab-ee`
- logging into gitlab with `root` and `testtesttest` once installed at port 80 from the ipv4 on the vm running gitlab
- creating a repo called whatever we wish maybe even "charts" as the name to mimic
- on the node going in and adding it as a remote to the cloned rancher charts repo, something like: `git remote add gitlab http://gitserver.192.168.104.197.sslip.io/root/rancher-charts-fork.git`
- then ensuring we are pulling down the appropriate branches from origin -> then pushing all the branches we need to the gitlab remote like `git push gitlab release-v2.7` -etc., logging in when it asks for the username: `root` and pw: `testtesttest`
- then we need to ensure in GitLab, that the repo we built is "public", not private - so it can be accessed by RKE1 cluster
- then we need to add it to Apps -> Repositories, putting in the http address and the respective branch
- then RKE1 is happy, and we can filter on charts for the GitLab (airgapped) repo, that it can communicate to, because all communication outbound to rancher would absolutely fail

# Screen Grab Demos
![Screenshot from 2024-06-07 12-04-15](https://github.com/harvester/tests/assets/5370752/f8169035-3e45-442a-bd89-ef4c343a5ab1)
![Screenshot from 2024-06-07 12-01-48](https://github.com/harvester/tests/assets/5370752/54bf4b51-fe8d-4256-aef6-6da59b6f9938)

# Reqs
- This just needs to be bundled in airgap automation, as we still have a high dependency to audit fully airgapped non-proxied environments
