### ISSUE TITLE
[DevOps] Provision Dual OpenStack Instances for Integrations w/ VM Import Controller

### ISSUE THREAD

**Issue by irishgordo** [harvester/tests#1815]
## OpenStack 2023.2/Stable (no longer Focal, dont let naming confuse, had to use Jammy):
- Jenkins Pipeline: http://FirstNumberofIPV4.SecondNumberofIPV4.1.7/blue/organizations/jenkins/harvester-vm-import-with-openstack/detail/harvester-vm-import-with-openstack/19/pipeline/ :
you can inspect the parameters to get an idea at what scale it's deployed at
- Sacrificial Harvester Cluster VM:
https://FirstNumberofIPV4.SecondNumberofIPV4.8.170/dashboard/harvester/c/local/kubevirt.io.virtualmachine/default/opnstk-server-vm-old#basics (admin/testtesttest)
`ssh ubuntu@FirstNumberofIPV4.SecondNumberofIPV4.0.191 pw: ubuntupw` (note, some info is also detailed in the tags of the VM on Harvester like username & password, in case it's forgotten)
- OpenStack Dashboard:
http://FirstNumberofIPV4.SecondNumberofIPV4.0.193/dashboard/project/
admin / testtesttest (additionally, for mention all info about the configuration of the deployment is available on Jenkins parameters to audit)
- Example VM http://FirstNumberofIPV4.SecondNumberofIPV4.0.193/dashboard/project/instances/5830a18e-5e0f-4698-8764-77022dd9870a/:
user: user / password: packer
(built with Packer, x-ref: https://github.com/irishgordo/tests/tree/feat/1534-vm-import-e2e-tests/packer_helpers )
## OpenStack 2024.2/Stable:
- note, this has more compute & storage than the other instance, but please reference the LOOP size in Jenkins Params and contrast that with Disk + Mem + CPU -> Disks are built on LVM off of LOOP
- Jenkins Pipeline: http://FirstNumberofIPV4.SecondNumberofIPV4.1.7/blue/organizations/jenkins/harvester-vm-import-with-openstack/detail/harvester-vm-import-with-openstack/10/pipeline
you can inspect the params to see how deployed
- Sacrificial Harvester Cluster VM:
https://FirstNumberofIPV4.SecondNumberofIPV4.8.170/dashboard/harvester/c/local/kubevirt.io.virtualmachine/default/opnstk-server-vm#basics (admin/testtesttest)
`ssh ubuntu@FirstNumberofIPV4.SecondNumberofIPV4.0.181 pw: ubuntupw`
## OpenStack Dashboard:
- http://FirstNumberofIPV4.SecondNumberofIPV4.0.183/
admin / testtesttest
- Example VM: http://FirstNumberofIPV4.SecondNumberofIPV4.0.183/dashboard/project/instances/13ad0b6d-d7b9-4bcc-a9c9-e0a5c78ecd8e/ :
user: user / password: packer
(built with Packer, x-ref: https://github.com/irishgordo/tests/tree/feat/1534-vm-import-e2e-tests/packer_helpers )

### Negotiating OpenStack CLI:

```yaml
clouds:
  openstack:
    auth:
      auth_url: REPLACE-ME
      username: "admin"
      project_id: REPLACE-ME
      project_name: "demo"
      user_domain_name: "Default"
      username: admin
      password: testtesttest
    region_name: "RegionOne"
    interface: "public"
    identity_api_version: 3
```
