### ISSUE TITLE
[TASK] AirGap Upgrade v1.4.2 -> v1.5.1-rc4

### ISSUE THREAD

**Issue by irishgordo** [harvester/tests#2070]
# Load-Out -

## Nodes:
- HP DL360 Gen 9, 128GB Mem, Intel(R) Xeon(R) CPU E5-2650L v3 @ 1.80GHz, Primary Disk SSD (800~GB), Secondary NVME (~1TB), Harvester OS Installed Primary SSD

### Rancher:
- 4 Cores
- 8Gi Mem
- 100Gi Disk
- K3S Version: v1.30.11+k3s1 (c2662fbe)
- Guest OS: Ubuntu 20.04.6 LTS
- Helm Installed Cert-Manager: v1.11.0
### DNS Server:
- Guest OS: Ubuntu 20.04.6 LTS
- 2 Cores
- 4Gi Mem
- 10Gi Disk
### Private Registry:
- 6 Cores
- 18Gi Mem
- 400Gi Disk
- Guest OS: Ubuntu 24.04.1 LTS
- Hauler version: 1.2.2
### NTP Server:
- Guest OS: Ubuntu 20.04.6 LTS
- 2 Cores
- 4Gi Mem
- 10Gi Disk
### MinIO Server (Single Node, Single Disk):
- 10Gi Root Disk
- 20Gi Data Disk
- 2 Cores
- 4Gi Mem
- Guest OS: Ubuntu 20.04.6 LTS
- MinIO Version: RELEASE.2024-12-18T13-15-44Z (commit-id=16f8cf1c52f0a77eeb8f7565aaf7f7df12454583)

**Comment by irishgordo** [comment]
# Prior to Rancher Prime v2.11.2 Upgrade (current Rancher Prime v2.10.4)
- 2 regular VMs 1 SLES15 SP6 (stopped vm), 1 SLES15 SP7 (running vm)
- 2 regular VMs snapshots (running, stopped)
- 2 regular VMs backups (running, stopped)
- Harvester IP Pool Built AirGap Compliant
- Harvester v1.4.2 3 node imported into Rancher v2.10.4
- Harvester UI Plugin Installed: 1.0.5
- Harvester UI Plugin Installed from:
    - Manage Extension Catalogs
    - Import Extension Catalog
    - Name: `ui-plugin-catalog` , Deployment Image: `airgap-docker-registry.10.115.55.115.sslip.io:5000/rancher/ui-plugin-catalog:4.0.1`
## RKE2 Clusters
1. SLES15-SP7:
   a. 2 Pool (1 CP+ETCD Pool with 1 node, 1 Worker Pool with 1 node)
   b. Each node, 4 Cores, 8Gi Mem, 40Gi Disk
   c. harvester-cloud-provider:0.2.900
   d. harvester-csi-driver:0.1.2300
   e. Guest OS: SLES15-SP7
```yaml
ngx1:
root@ngx1-78dfc586b7-952pf:/# echo "sles15-sp7-ngx1" > /mnt/ngx1-1g-vol/sles15-sp7-ngx1.txt
root@ngx1-78dfc586b7-952pf:/# cat /mnt/ngx1-1g-vol/sles15-sp7-ngx1.txt 
sles15-sp7-ngx1
root@ngx1-78dfc586b7-952pf:/# md5sum /mnt/ngx1-1g-vol/sles15-sp7-ngx1.txt 
4fc1b3eef84d2f346aaa3ddc1c1940a9  /mnt/ngx1-1g-vol/sles15-sp7-ngx1.txt
ngx2:
root@ngx2-54c8df4d6b-55p2l:/# echo "sles15-sp7-ngx2" > /mnt/ngx2-2g-vol/sles15-sp7-ngx2.txt
root@ngx2-54c8df4d6b-55p2l:/# cat /mnt/ngx2-2g-vol/sles15-sp7-ngx2.txt 
sles15-sp7-ngx2
root@ngx2-54c8df4d6b-55p2l:/# md5sum /mnt/ngx2-2g-vol/sles15-sp7-ngx2.txt 
14aaa0879472e129f5067eb381ae3240  /mnt/ngx2-2g-vol/sles15-sp7-ngx2.txt
```
2. SLES15-SP6:
   a. 2 Pool (1 CP+ETCD Pool with 1 node, 1 Worker Pool with 1 node)
   b. Each node, 4 Cores, 8Gi Mem, 40Gi Disk
   c. harvester-cloud-provider:0.2.900
   d. harvester-csi-driver:0.1.2300
   e. Guest OS: SLES15-SP6
```yaml
ngx1:
root@ngx1-7b94477c94-n9crh:/# echo "sles15-sp6-ngx1" > /mnt/ngx1-1g-vol/sles15-sp6-ngx1.txt
root@ngx1-7b94477c94-n9crh:/# cat /mnt/ngx1-1g-vol/sles15-sp6-ngx1.txt 
sles15-sp6-ngx1
root@ngx1-7b94477c94-n9crh:/# md5sum /mnt/ngx1-1g-vol/sles15-sp6-ngx1.txt 
d312e13c8cf6701eb95c7325074f06ca  /mnt/ngx1-1g-vol/sles15-sp6-ngx1.txt
ngx2:
root@ngx2-8588cfd79c-s7gcg:/# echo "sles15-sp6-ngx2" > /mnt/ngx2-2g-vol/sles15-sp6-ngx2.txt
root@ngx2-8588cfd79c-s7gcg:/# cat /mnt/ngx2-2g-vol/sles15-sp6-ngx2.txt 
sles15-sp6-ngx2
root@ngx2-8588cfd79c-s7gcg:/# md5sum /mnt/ngx2-2g-vol/sles15-sp6-ngx2.txt 
9e5fcdb2c033ae47bc3fd8dacc95b408  /mnt/ngx2-2g-vol/sles15-sp6-ngx2.txt
```
3. additional registries on RKE2 Guest Clusters set up appropriately 
4. additional manifest for RKE2 Guest Clusters, YAML:
```yaml
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  annotations:
    field.cattle.io/description: nginx-1-1g-vol
    volume.beta.kubernetes.io/storage-provisioner: driver.harvesterhci.io
    volume.kubernetes.io/storage-provisioner: driver.harvesterhci.io
  labels:
    svc: ngx1
  name: nginx-1-1g
  namespace: default
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: harvester
  volumeMode: Filesystem
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  annotations:
    field.cattle.io/description: nginx-2-2g-vol
    volume.beta.kubernetes.io/storage-provisioner: driver.harvesterhci.io
    volume.kubernetes.io/storage-provisioner: driver.harvesterhci.io
  labels:
    svc: ngx2
  name: nginx-2-2g
  namespace: default
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
  storageClassName: harvester
  volumeMode: Filesystem
---
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    field.cattle.io/description: nginx 1 deployment
  labels:
    workload.user.cattle.io/workloadselector: apps.deployment-default-ngx1
  name: ngx1
  namespace: default
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      workload.user.cattle.io/workloadselector: apps.deployment-default-ngx1
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        svc: ngx1
        workload.user.cattle.io/workloadselector: apps.deployment-default-ngx1
      namespace: default
    spec:
      affinity: {}
      containers:
        - image: airgap-docker-registry.10.115.55.115.sslip.io:5000/library/nginx:latest
          imagePullPolicy: IfNotPresent
          name: ngx1
          resources: {}
          securityContext:
            allowPrivilegeEscalation: false
            privileged: false
            readOnlyRootFilesystem: false
            runAsNonRoot: false
          stdin: true
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          tty: true
          volumeMounts:
            - mountPath: /mnt/ngx1-1g-vol
              name: vol-ngx1-1g
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
        - name: vol-ngx1-1g
          persistentVolumeClaim:
            claimName: nginx-1-1g
---
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    field.cattle.io/description: nginx 2 deployment
  labels:
    workload.user.cattle.io/workloadselector: apps.deployment-default-ngx2
  name: ngx2
  namespace: default
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      workload.user.cattle.io/workloadselector: apps.deployment-default-ngx2
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        svc: ngx2
        workload.user.cattle.io/workloadselector: apps.deployment-default-ngx2
      namespace: default
    spec:
      affinity: {}
      containers:
        - image: airgap-docker-registry.10.115.55.115.sslip.io:5000/library/nginx:latest
          imagePullPolicy: IfNotPresent
          name: ngx2
          resources: {}
          securityContext:
            allowPrivilegeEscalation: false
            privileged: false
            readOnlyRootFilesystem: false
            runAsNonRoot: false
          stdin: true
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          tty: true
          volumeMounts:
            - mountPath: /mnt/ngx2-2g-vol
              name: vol-ngx2-2g
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
        - name: vol-ngx2-2g
          persistentVolumeClaim:
            claimName: nginx-2-2g
---
apiVersion: v1
kind: Service
metadata:
  annotations:
    cloudprovider.harvesterhci.io/ipam: dhcp
    field.cattle.io/description: ipam lb ngx1
  finalizers:
    - service.kubernetes.io/load-balancer-cleanup
  name: lb-ngx1-ipam
  namespace: default
spec:
  allocateLoadBalancerNodePorts: true
  externalTrafficPolicy: Cluster
  internalTrafficPolicy: Cluster
  ipFamilies:
    - IPv4
  ipFamilyPolicy: SingleStack
  ports:
    - name: ngx1lb
      nodePort: 30001
      port: 8080
      protocol: TCP
      targetPort: 80
  selector:
    svc: ngx1
  sessionAffinity: None
  type: LoadBalancer
---
apiVersion: v1
kind: Service
metadata:
  annotations:
    cloudprovider.harvesterhci.io/ipam: pool
    field.cattle.io/description: pool lb ngx2
  finalizers:
    - service.kubernetes.io/load-balancer-cleanup
  name: lb-ngx2-pool
  namespace: default
spec:
  allocateLoadBalancerNodePorts: true
  externalTrafficPolicy: Cluster
  internalTrafficPolicy: Cluster
  ipFamilies:
    - IPv4
  ipFamilyPolicy: SingleStack
  ports:
    - name: ngx2lb
      nodePort: 30002
      port: 8080
      protocol: TCP
      targetPort: 80
  selector:
    svc: ngx2
  sessionAffinity: None
  type: LoadBalancer
```
5. load-balancers & pvcs working / looking good as expected


![Image](https://github.com/user-attachments/assets/4872651c-ed2b-46e7-9624-3319e6b0b747)
![Image](https://github.com/user-attachments/assets/4eacb4aa-ff6b-413b-bbc0-96485bb52bb8)
![Image](https://github.com/user-attachments/assets/4070136b-2355-4508-8dea-214680de1580)
![Image](https://github.com/user-attachments/assets/229b6ebd-6efe-4c89-82d3-c6fe3848b23a)
![Image](https://github.com/user-attachments/assets/d35fea55-1e62-4080-90bb-31b31dae11b1)
