### ISSUE TITLE
[bug][DevOps] vagrant-libvirt doesn't get installed with provisioning scripts

### ISSUE THREAD

**Issue by irishgordo** [harvester/tests#668]
Provisioning scripts, seem to not install vagrant libvirt plugin.
Though on install_vagrant.yml list as:
```yaml
- name: jenkins | install_vagrant |
        Install vagrant-libvirt plugin for jenkins user
  become: true
  become_user: jenkins
  shell: >
    vagrant plugin install vagrant-libvirt
```

Error pops up with:
```
ubuntu@test-jenkins-ci-main-node:/var/lib/jenkins/workspace/airgap-harvester-airgap-rancher-vagrant-installation-test/ipxe-examples/vagrant-pxe-airgap-harvester$ vagrant destroy -f
Required plugin 'vagrant-libvirt' is missing; please install using:
  % vagrant plugin install vagrant-libvirt

```
